# Generated by Django 4.2.21 on 2025-05-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='original_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
