# Generated by Django 5.2.6 on 2025-10-17 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlines', '0001_initial'),
        ('templates_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_config.template'),
        ),
    ]
