# Generated by Django 5.2.6 on 2025-10-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlines', '0002_outline_original_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='title_setting',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
